export const environment = {
  production: true,
  server:'https://yetena.balemuya.com',
  balemuyaEndPoint: '/ajax.php?action=addBalemuya',
  volunteerEndPoint: '/ajax.php?action=addVolunteer',
  dashboardEndPoint: '/ajax.php?action=dashboard',
  individualUpdateEndPoint: '/ajax.php?action=update-individual',
  individualAddressUpdateEndPoint: '/ajax.php?action=update-individual-address',
  authEndPoint: '/ajax.php?action=login',
  requestEndPoint: '/ajax.php?action=request',
  requestListEndPoint: '/ajax.php?action=list-request',
  requestByIdEndPoint: '/ajax.php?action=request-by-id',
  requestPickedEndPoint: '/ajax.php?action=request-picked',
  addCommentEndPoint: '/ajax.php?action=add-comment',
  awesomeVolunteerEndPoint: '/ajax.php?action=awesome-volunteers',
  professionalListEndPoint: '/ajax.php?action=list-professionals',
  volunteerListEndPoint: '/ajax.php?action=list-volunteers',
  oAuthLogin: '/ajax.php?action=oauth-login',
  statesEndPoint: '/ajax.php?action=list-states',
  citiesEndPoint: '/ajax.php?action=list-cities',
  firebase: {
    apiKey: "AIzaSyCWj9mkUKqWAkywvXkK0-wg8X4OSyHXhpw",
    authDomain: "login-ng-a0220.firebaseapp.com",
    databaseURL: "https://login-ng-a0220.firebaseio.com",
    projectId: "login-ng-a0220",
    storageBucket: "login-ng-a0220.appspot.com",
    messagingSenderId: "620412013881",
    appId: "1:620412013881:web:1bb10969de99cacc90ece8"
  }
};
